## Importando librerías

In [2]:
import numpy as np

### Arange

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Zeros

In [5]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Ones

In [6]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Linspace

In [7]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

### Eye

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random

In [9]:
np.random.rand()

0.6307719759320619

In [10]:
np.random.rand(4)

array([0.12862498, 0.97509415, 0.88524864, 0.28579763])

In [11]:
np.random.rand(1)

array([0.97073851])

In [12]:
np.random.rand(4,4)

array([[0.72214281, 0.19861975, 0.2369654 , 0.36220078],
       [0.54474038, 0.37795701, 0.31605283, 0.95202204],
       [0.45712416, 0.42527631, 0.17854921, 0.3107801 ],
       [0.66097665, 0.99553202, 0.47006813, 0.96947345]])

In [31]:
np.random.rand(5,4)

array([[0.17514366, 0.75012883, 0.56331454, 0.72679565],
       [0.75252239, 0.5134988 , 0.92575982, 0.66621954],
       [0.8619754 , 0.08566498, 0.48504789, 0.79034513],
       [0.44084818, 0.54980932, 0.04037484, 0.74101972],
       [0.19275246, 0.25563926, 0.21738648, 0.57477428]])

In [32]:
np.random.rand(4,5)

array([[0.94977516, 0.38905861, 0.11914234, 0.421254  , 0.075881  ],
       [0.91948951, 0.97755095, 0.29904039, 0.10116437, 0.21819317],
       [0.90883189, 0.21416   , 0.74538592, 0.95084401, 0.19693539],
       [0.71007326, 0.00821676, 0.25760899, 0.12888976, 0.89780445]])

In [13]:
np.random.randint(1,15)

5

In [14]:
np.random.randint(1,100,(10,10))

array([[43, 86, 24, 61, 24, 98,  8, 20, 61, 18],
       [84, 93, 20,  1, 11, 43, 72, 27, 52, 92],
       [57, 32, 29, 30, 64, 64, 83, 24, 81, 90],
       [13, 53, 11, 60,  5, 72, 81, 81,  7,  2],
       [ 1, 18, 23,  4, 42, 74, 14, 56,  4, 13],
       [89, 97, 21, 76, 60, 82, 89, 11, 84, 77],
       [28, 48, 66,  2, 54, 29,  1,  7, 38, 72],
       [51, 78, 23, 94, 24, 54, 44, 42, 10, 50],
       [ 4, 19, 25, 64, 21, 49, 18, 72, 26, 97],
       [39,  6, 76, 90, 70, 61, 53, 74, 79, 12]])