## Importando librerías

In [2]:
import numpy as np

### Arange

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Zeros

In [5]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Ones

In [6]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Linspace

In [7]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

### Eye

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random

In [9]:
np.random.rand()

0.29838796594990347

In [10]:
np.random.rand(4)

array([0.72109739, 0.23850701, 0.8023532 , 0.61723364])

In [11]:
np.random.rand(4,4)

array([[0.71848774, 0.6869663 , 0.04749603, 0.01843245],
       [0.18057553, 0.84425284, 0.42689111, 0.06338784],
       [0.43249785, 0.72113983, 0.37086847, 0.121854  ],
       [0.14687648, 0.93099768, 0.87545456, 0.77067358]])

In [12]:
np.random.randint(1,15)

12

In [13]:
np.random.randint(1,100,(10,10))

array([[32,  5, 16,  4, 26,  3, 12, 89, 40, 98],
       [31, 72, 74, 82, 14, 90, 10, 64, 49, 18],
       [46, 26,  2, 26, 42, 90, 40, 51, 34,  6],
       [82,  3, 90, 77, 55, 82,  7, 73, 68, 11],
       [63, 67, 73, 39, 26, 98,  4, 63, 92, 43],
       [10, 11, 25, 95, 26, 68,  7, 53, 24, 65],
       [80,  2, 33, 13, 70, 83, 19, 89, 68, 13],
       [89, 84, 99, 26, 11, 63, 68, 46, 89, 25],
       [79, 99, 12, 13, 99, 58, 54, 62, 30, 34],
       [33, 99, 62, 19, 45, 90,  7,  2, 82, 93]])