## Importar librería

In [28]:
import numpy as np

## Definiendo arrays

In [29]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

#'.ndim': number of dimensions

In [30]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [31]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [32]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6],[7,8,9],[0,2,45]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]]


3

## Agregar o eliminar dimensiones

In [33]:
vector = np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

# axis=0 for rows 
# axis=1 for columns
# expand the number of dimensions

In [34]:
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [35]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)


[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


## Retos

In [45]:
# Definir un tensor de 5D

tensor_5d = np.array([[[[[1,2],[2,3],[2,3],[3,4],[4,5],[5,6]],[[1,2],[2,3],[2,3],[3,4],[4,5],[5,6]]]]])
print(tensor_5d)
tensor_5d.ndim

[[[[[1 2]
    [2 3]
    [2 3]
    [3 4]
    [4 5]
    [5 6]]

   [[1 2]
    [2 3]
    [2 3]
    [3 4]
    [4 5]
    [5 6]]]]]


5

In [46]:
# Sumarle una dimensión en cualquier eje

expand = np.expand_dims(tensor_5d, axis=1)  
print(expand)
expand.ndim

[[[[[[1 2]
     [2 3]
     [2 3]
     [3 4]
     [4 5]
     [5 6]]

    [[1 2]
     [2 3]
     [2 3]
     [3 4]
     [4 5]
     [5 6]]]]]]


6

In [47]:
# Borrar las dimensiones que no se usen
expand = np.squeeze(expand)
print(expand, expand.ndim)

[[[1 2]
  [2 3]
  [2 3]
  [3 4]
  [4 5]
  [5 6]]

 [[1 2]
  [2 3]
  [2 3]
  [3 4]
  [4 5]
  [5 6]]] 3
