### Importar librerías

In [2]:
import numpy as np 

In [3]:
arr = np.random.randint(1,10,(3,2))

### Shape

In [4]:
arr.shape

(3, 2)

In [5]:
arr

array([[7, 3],
       [3, 3],
       [7, 2]])

### Reshape

In [6]:
arr.reshape(1,6)

array([[7, 3, 3, 3, 7, 2]])

In [7]:
arr.reshape(2,3)

array([[7, 3, 3],
       [3, 7, 2]])

In [8]:
np.reshape(arr,(1,6))

array([[7, 3, 3, 3, 7, 2]])

In [9]:
arr

array([[7, 3],
       [3, 3],
       [7, 2]])

In [10]:
np.reshape(arr,(2,3),'C')

array([[7, 3, 3],
       [3, 7, 2]])

In [11]:
np.reshape(arr,(2,3),'F')

array([[7, 7, 3],
       [3, 3, 2]])

In [12]:
np.reshape(arr,(2,3),'A')

array([[7, 3, 3],
       [3, 7, 2]])

## Retos

In [43]:
tensor_5d = np.array([[[[[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18],[19,20],[21,22],[23,24]]]]])
tensor = np.squeeze(tensor_5d)
#print(f'{tensor}')
print(tensor.ndim)
print(tensor.shape)
new_tensor = np.reshape(tensor, (6,4))
print(new_tensor, new_tensor.shape)
print(new_tensor.ndim)

3
(2, 6, 2)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]] (6, 4)
2


In [46]:
# Intenta cambiar el array de forma que no respete la estructura original
new_tensor = np.reshape(tensor, (4,66))
new_tensor

ValueError: cannot reshape array of size 24 into shape (4,66)